### ISSUE TITLE
How can I use this plugin with babel-loader?

### ISSUE THREAD

**Issue by puttyman** [ant-design/babel-plugin-import#145]
When I use it in my webpack config as such:

```js      
{
        test: /\.jsx?$/,
        loader: 'babel-loader',
        include: [
          path.resolve(__dirname, '../src'),
        ],
        query: {
          cacheDirectory: isDebug,

          babelrc: false,
          presets: [
            ['env', {
              targets: {
                browsers: pkg.browserslist,
              },
              modules: false,
              useBuiltIns: false,
              debug: false,
            }],
            'stage-2',
            'react',
            ...isDebug ? [] : ['react-optimize'],
          ],
          plugins: [
            'transform-decorators-legacy',
            ...isDebug ? ['transform-react-jsx-source'] : [],
            ...isDebug ? ['transform-react-jsx-self'] : [],
            ["import", { "libraryName": "antd", "style": "css" }]
          ],
        },
      },
```

I get the errors below. It seems that babel tries to compile the included css.

```shell
webpack: Compiled successfully.
/Users/user/project/node_modules/antd/lib/style/index.css:9
html {
     ^

SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/issues/96

**Comment by puttyman** [comment]
I am still having issues with this. I am trying to use it with https://github.com/kriasoft/react-starter-kit

**Comment by tim-soft** [comment]
I am also having issues incorporating ant-design into react-starter-kit, their webpack config has evolved quite a bit and now [this commit from ant-design fork](https://github.com/ant-design/react-starter-kit/commit/6e345f69bf7dd639ca2c56e4f51f928926c0ee76) doesn't apply anymore.

I'll post a solution here when I figure it out

**Comment by Ancinek** [comment]
Did you guys solve it? Same problem here.

**Comment by tim-soft** [comment]
@Ancinek  https://github.com/ant-design/ant-design/issues/5171#issuecomment-348384605

**Comment by justQing00** [comment]
当为服务器的时候，不进行处理即可
[https://github.com/zeit/next-plugins/issues/70](https://github.com/zeit/next-plugins/issues/70)
