### ISSUE TITLE
使用redux-saga出错

### ISSUE THREAD

**Issue by szouc** [ant-design/babel-plugin-import#152]
webpack 配置
```
test: /\.(js|jsx)$/,
        use: [
          {
            // https://github.com/babel/babel-loader
            loader: 'babel-loader',
            options: {
              // https://babeljs.io/docs/usage/api/#options
              cacheDirectory: !isProd,
              babelrc: false,
              presets: [
                // https://babeljs.io/docs/plugins/#presets
                ['env', {
                  modules: false,
                  useBuiltIns: false,
                  debug: false
                }],
                'react',
                'stage-2',
                'flow'
              ],
              plugins: [
                // https://babeljs.io/docs/plugins
                ['transform-runtime'],
                ['import', {
                  libraryName: 'antd',
                  libraryDirectory: 'lib',
                  style: 'css'
                }],
                ['flow-react-proptypes'],
                ...isProd ? [] : ['react-hot-loader/babel'],
                ...isProd ? [] : ['transform-react-jsx-source'],
                ...isProd ? [] : ['transform-react-jsx-self']
              ]
            }
          }
        ],
```

Sagas：

```
// flow-disable-next-line
function * watchRequestHello () {
  yield takeEvery(SAY_HELLO_ASYNC_REQUEST, handleRequestHello)
}

export default watchRequestHello
```

报错：

```
ERROR in ./src/client/saga/hello.js
Module build failed: TypeError: G:/Project/mLesson/src/client/saga/hello.js: Cannot read property 'file' of undefined
    at Plugin.ReturnStatement (G:\Project\mLesson\node_modules\babel-plugin-import\lib\Plugin.js:223:26)
    at applyInstance (G:\Project\mLesson\node_modules\babel-plugin-import\lib\index.js:27:26)
    at PluginPass.ret.visitor.(anonymous function) (G:\Project\mLesson\node_modules\babel-plugin-import\lib\index.js:87:9)
    at newFn (G:\Project\mLesson\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (G:\Project\mLesson\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (G:\Project\mLesson\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (G:\Project\mLesson\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (G:\Project\mLesson\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (G:\Project\mLesson\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (G:\Project\mLesson\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (G:\Project\mLesson\node_modules\babel-traverse\lib\index.js:114:17)
 @ ./src/client/index.jsx 18:0-45
```

**Comment by yesmeck** [comment]
看起来不是 babel-plugin-import 的问题，请先确认下是不是 babel-plugin-import 的问题。如果有问题请提供重现的 repo。
