### ISSUE TITLE
An error in babel 7.0.0-beta.2

### ISSUE THREAD

**Issue by duan602728596** [ant-design/babel-plugin-import#180]
When the version of Babel is 7.0.0-beta.2, there is an error using babel-plugin-import.
```
ERROR in ./src/app.js
Module build failed: TypeError: D:\project\code\src\app.js: Cannot read property 'file' of undefined
    at Plugin.buildExpressionHandler (D:\project\code\node_modules\babel-plugin-import\lib\Plugin.js:72:26)
    at Plugin.IfStatement (D:\project\code\node_modules\babel-plugin-import\lib\Plugin.js:207:12)
    at applyInstance (D:\project\code\node_modules\babel-plugin-import\lib\index.js:27:26)
    at PluginPass.ret.visitor.(anonymous function) (D:\project\code\node_modules\babel-plugin-import\lib\index.js:89:9)
    at newFn (D:\project\code\node_modules\babel-traverse\lib\visitors.js:236:21)
    at NodePath._call (D:\project\code\node_modules\babel-traverse\lib\path\context.js:68:19)
    at NodePath.call (D:\project\code\node_modules\babel-traverse\lib\path\context.js:42:17)
    at NodePath.visit (D:\project\code\node_modules\babel-traverse\lib\path\context.js:99:12)
    at TraversalContext.visitQueue (D:\project\code\node_modules\babel-traverse\lib\context.js:137:18)
    at TraversalContext.visitMultiple (D:\project\code\node_modules\babel-traverse\lib\context.js:91:17)
 @ multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=500&reload=true ./src/app.js

```

**Comment by pigcan** [comment]
https://github.com/ant-design/babel-plugin-import/pull/179

稍后会发布一个 2.0 版本用来支持 babel 7
