### ISSUE TITLE
在 jest --coverage 时候会报错

### ISSUE THREAD

**Issue by someok** [ant-design/babel-plugin-import#189]
单纯 jest 测试的时候正常，但是配合 `--coverage` 的时候就报错了，后来去掉 `import` 那部分配置就 OK 了

报错信息类似下面这样的：
```
    ReferenceError: Input is not defined
      
      at Object.<anonymous> (app/container/admin/request/ValidateModal.js:11:1)
      at Object.<anonymous> (app/container/admin/request/__tests__/ValidateModal.test.js:10:22)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:125:13)
      at process.emit (events.js:213:7)
      at emit (internal/child_process.js:774:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

```

虽然有个解决办法就是把 import 配置转移到各个 env 下面，但是这样毕竟不够优雅，想知道有没有啥开关可以在 `test` 部分配置一下？

我的 `.babelrc` 配置如下：
```
{
    "presets": [
        [
            "env",
            {
                "modules": false
            }
        ],
        "stage-0",
        "react"
    ],
    "plugins": [
        "transform-decorators-legacy",
        "transform-decorators",
        "lodash",
        [
            "import",
            [
                {
                    "libraryName": "antd",
                    "style": true
                }
            ]
        ]
    ],
    "env": {
        "test": {
            "sourceMap": "inline",
            "plugins": [
                "transform-es2015-modules-commonjs",
                "dynamic-import-node"
            ]
        },
        "devHmr": {
            "plugins": [
                "react-hot-loader/babel"
            ]
        },
        "production": {
            "plugins": [
                [
                    "transform-react-remove-prop-types",
                    {
                        "removeImport": true
                    }
                ]
            ]
        }
    }
}

```

**Comment by pascalduez** [comment]
Refs #207 172

**Comment by yesmeck** [comment]
测试环境其实没必要用这个。

**Comment by someok** [comment]
对啊，我的意思就是希望有个disable的配置项，只需要在test env下配置一次就行了

**Comment by yesmeck** [comment]
https://babeljs.io/docs/usage/babelrc/#env-option

**Comment by pascalduez** [comment]
Would you mind providing an English explanation please? Might be handy for future references.

**Comment by yesmeck** [comment]
@pascalduez Don't use `babel-plugin-import` in test environment.

**Comment by pascalduez** [comment]
@yesmeck Thanks! That also the conclusion I ended up with.

**Comment by kive323** [comment]
> @pascalduez Don't use `babel-plugin-import` in test environment.

Thanks a lot. After hours of researches, it's the unique answer that saves my life.

**Comment by susan-github** [comment]
![14_27_48__12_07_2018](https://user-images.githubusercontent.com/9947305/49631298-62545880-fa2c-11e8-88d8-74aea19cf637.jpg)

I have removed the 'import' config in testing environment，but still get 'undefined' error.

**Comment by kive323** [comment]
> @kive323 how to disabled babel-plugin-import in test environment?

Here is my `.babelrc` config.
```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime"
  ],
  "env": {
    "dev": {
      "plugins": [
        [
          "import",
          { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }
        ]
      ]
    },
    "production": {
      "plugins": [
        [
          "import",
          { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }
        ]
      ]
    }
  }
}
```
I only enable babel-plugin-import in dev and production environment.

**Comment by mgcrea** [comment]
If you're use a `babel.config.js`, here is what you can do:

```js
const {NODE_ENV = 'development'} = process.env;
const presets = ['react-app', '@babel/preset-typescript'];
const plugins = [
  [
    'named-asset-import',
    {
      loaderMap: {
        svg: {
          ReactComponent: '@svgr/webpack?-svgo,+titleProp,+ref![path]'
        }
      }
    }
  ],
  [
    'module-name-mapper',
    {
      moduleNameMapper: {
        '^src/(.*)': '<rootDir>/src/$1'
      }
    }
  ],
  'react-hot-loader/babel'
];

if (NODE_ENV !== 'test') {
  plugins.push(['import', {libraryName: 'antd', libraryDirectory: 'es', style: 'css'}]);
}

module.exports = {
  presets,
  plugins
};
```

**Comment by davidtong** [comment]
To disable babel-plugin-import in test:

```
  "env": {
    "test": {
      "plugins": [
        ["import", false]
      ],
      ...
```
