### ISSUE TITLE
next.js加入babel-plugin-import使用antd时，无法加载到样式

### ISSUE THREAD

**Issue by supeng911** [ant-design/babel-plugin-import#207]
.babelrc:
`
{
    "presets": ["next/babel"],
    "plugins": [
      "transform-decorators-legacy",
      ["import", { "libraryName": "antd", "style": true }]
    ]
  }
`

这样的配置，运行时会报错：Invalid or unexpected token
/next-test/node_modules/antd/lib/style/index.less:1
(function (exports, require, module, __filename, __dirname) { @import "./themes/default";

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/speeder/WorkSpace/JavaScript/next-test/node_modules/antd/lib/form/style/index.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

**Comment by yesmeck** [comment]
`next.js` 的问题。参考 https://github.com/zeit/next.js/blob/canary/examples/with-ant-design/README.md 来配置
