### ISSUE TITLE
Eslint 报错: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by andong-lad** [ant-design/babel-plugin-import#237]
项目中安装此 babel 插件后，执行 eslint 会报错： 

```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/anto/Projects/music-all/music-vip/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```

不装此插件则不会报错。 

我的关键版本信息：

```
"babel-eslint": "^8.2.3",
"eslint": "^4.19.1",
"eslint-plugin-import": "^2.12.0",
"eslint-plugin-react": "^7.8.2",
"babel-core": "^6.26.3",
"babel-plugin-import": "^1.7.0",
```

**Comment by andong-lad** [comment]
忽略。查到问题不是这个原因。
