### ISSUE TITLE
你好，我运行 npm run build 出现了babel错误

### ISSUE THREAD

**Issue by kvkens** [ant-design/babel-plugin-import#265]
源码下载后 npm install 安装好，运行 `npm run build`之后出现了下面的错误，请问下是什么原因呢？
babel已经按照最新的7更新的.

```bash
> rm -rf lib && ./node_modules/.bin/babel src --out-dir lib --ignore __tests__

Error: [BABEL] /Users/kvkens/ac/babel-plugin-import-bee/src/Plugin.js: The pipeline operator plugin requires a 'proposal' option.'proposal' must be one of: minimal. More details:https://babeljs.io/docs/en/next/babel-plugin-proposal-pipeline-operator (While processing: "/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/plugin-proposal-pipeline-operator/lib/index.js$inherits")
    at _default (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/plugin-syntax-pipeline-operator/lib/index.js:27:11)
    at /Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPluginDescriptor (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/full.js:200:28)
    at cache.invalidate.data (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/full.js:224:47)
    at CacheConfigurator.invalidate (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/caching.js:150:17)
    at instantiatePlugin (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/full.js:224:28)
    at cachedFunction (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPluginDescriptor (/Users/kvkens/ac/babel-plugin-import-bee/node_modules/@babel/core/lib/config/full.js:200:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! babel-plugin-import-bee@1.1.0-beta.1 build: `rm -rf lib && ./node_modules/.bin/babel src --out-dir lib --ignore __tests__`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-plugin-import-bee@1.1.0-beta.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kvkens/.npm/_logs/2018-08-30T05_40_16_865Z-debug.log
```

**Comment by sorrycc** [comment]
babel-plugin-import-bee?

**Comment by kvkens** [comment]
@sorrycc hello 云谦，我是基于rc组件封装的组件，直接使用了这个插件，后面可能是babel7的方法有问题，我也没找出，我目前先不使用了，先关了哈！
