### ISSUE TITLE
babel已经升级到7了。该插件不兼容

### ISSUE THREAD

**Issue by BillyQin** [ant-design/babel-plugin-import#350]
项目之前babel-core版本是6.23。运行正常。
现在升级到@babel/core，运行报错。
```
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.6.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-stage-0": "^7.0.0",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-import": "^1.12.0",
```

**Comment by BillyQin** [comment]
webpack.config.js
```
  {
        test: /\.(js|jsx)$/,
        include: path.resolve(__dirname, '../src'),
        use: [
          {
            loader: 'babel-loader',
            options: {
              plugins: [
                [
                  'import',
                  [
                    { libraryName: 'antd', style: true },
                  ],
                ],
                ['@babel/plugin-proposal-decorators', { 'legacy': true }],
                '@babel/plugin-syntax-dynamic-import',
                ['@babel/plugin-proposal-class-properties', { 'loose': true }],
              ],
              presets: [
                '@babel/preset-env',
                '@babel/preset-react',
              ],
              cacheDirectory: true,
            },
          },
        ],
      },
```
error
```
ERROR in ./views/src/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .plugins[0][1] must be an object, false, or undefined
    at assertPluginItem (/Users/test/node_modules/@babel/core/lib/config/validation/option-assertions.js:244:15)
    at arr.forEach (/Users/test/node_modules/@babel/core/lib/config/validation/option-assertions.js:222:30)
    at Array.forEach (<anonymous>)
    at assertPluginList (/Users/test/node_modules/@babel/core/lib/config/validation/option-assertions.js:222:9)
    at Object.keys.forEach.key (/Users/test/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/test/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/test/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/test/node_modules/@babel/core/lib/config/partial.js:66:50)
    at Object.loadPartialConfig (/Users/test/node_modules/@babel/core/lib/config/partial.js:110:18)
 @ multi ./views/src/index.jsx app[0]
ℹ ｢wdm｣: Failed to compile.
```

**Comment by BillyQin** [comment]
参数无需数组包裹。
```
options: {
              plugins: [
                [
                  'import',
                    { libraryName: 'antd', style: true }
                ],
                ['@babel/plugin-proposal-decorators', { 'legacy': true }],
                '@babel/plugin-syntax-dynamic-import',
                ['@babel/plugin-proposal-class-properties', { 'loose': true }],
              ],
```
