### ISSUE TITLE
webpack2 的一个配置项与 CSS Auto Import. 冲突

### ISSUE THREAD

**Issue by p2227** [ant-design/babel-plugin-import#54]
当我们使用webpack2的时候，babelrc会这样配置：（配合^6.13版本的babel）

```
"presets": [
    ["es2015",{
      "modules":false
    }],
    "react",
    "stage-0"
  ],
```

而webpack1会这样

```
"presets": [ "es2015","react","stage-0" ]
```

对于这样一份源代码

```
import React from 'react';
import ReactDom from 'react-dom';
import { Button } from 'antd';

ReactDOM.render(<div>
  <Button>xxxx</Button>
</div>, document.getElementById('react-container'));
```

webpack2的配置会编译成这样

```
import React from 'react';
import ReactDom from 'react-dom';
import { Button } from 'antd';

ReactDOM.render(React.createElement(
  'div',
  null,
  React.createElement(
    Button,
    null,
    'xxxx'
  )
), document.getElementById('react-container'));
```

webpack1的配置会编译成这样

```
var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _reactDom = require('react-dom');

var _reactDom2 = _interopRequireDefault(_reactDom);

var _antd = require('antd');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

ReactDOM.render(_react2.default.createElement(
  'div',
  null,
  _react2.default.createElement(
    _antd.Button,
    null,
    'xxxx'
  )
), document.getElementById('react-container'));

```

前者配合 babel-plugin-antd，配置`style:true` 的时候 编译阶段就会报这个错误 https://github.com/ant-design/babel-plugin-antd/issues/43 

可能重现会比较麻烦，我这边自己试了是跟 import 的语法有关系，可能是里面遍历ast的时候有bug。官方有跟webpack2配合的例子？

**Comment by p2227** [comment]
这个bug最简单的一个解决方法是在这里
https://github.com/ant-design/babel-plugin-antd/blob/6284a4d322d8cfce2cc48c6158abe6c45a043617/src/Plugin.js#L21
和这里
https://github.com/ant-design/babel-plugin-antd/blob/6284a4d322d8cfce2cc48c6158abe6c45a043617/src/Plugin.js#L23
加上一个imported标识符，比如
```
file.addImport(`${path}/style`,'style');
```
但是这会令到以前import style的语句发生变化 （效果是一样的，就是多了标识 符）。

如果 不想要这个标识，那要修改
https://github.com/ant-design/babel-plugin-antd/blob/6284a4d322d8cfce2cc48c6158abe6c45a043617/src/Plugin.js#L14
importMethod函数的入参，传入 babel的path，改变挻 大的，不知道哪一种方案好呢？

**Comment by czl1378** [comment]
@p2227 第一种方案应该要好点

**Comment by jameswyse** [comment]
Seems the second argument to `addImport` is required: https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/index.js#L253

I was getting babel errors when I enabled the `style: 'css'` option, but adding a second argument fixed it. I changed it to `file.addImport(`${path}/style`,'*');` but it seems to work with any value.

```
Cannot read property 'length' of null
     at Buffer._append (node_modules/babel-generator/lib/buffer.js:83:25)
     at Buffer.append (node_modules/babel-generator/lib/buffer.js:55:10)
     at Generator._append (node_modules/babel-generator/lib/printer.js:206:52)
     at Generator.word (node_modules/babel-generator/lib/printer.js:131:10)
     at Generator.Identifier (node_modules/babel-generator/lib/generators/types.js:38:8)
     at node_modules/babel-generator/lib/printer.js:298:23
     at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:142:28)
     at Generator.withSource (node_modules/babel-generator/lib/printer.js:189:15)
     at Generator.print (node_modules/babel-generator/lib/printer.js:297:10)
     at Generator.ImportSpecifier (node_modules/babel-generator/lib/generators/modules.js:22:8)
     at node_modules/babel-generator/lib/printer.js:298:23
     at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:142:28)
     at Generator.withSource (node_modules/babel-generator/lib/printer.js:189:15)
     at Generator.print (node_modules/babel-generator/lib/printer.js:297:10)
     at Generator.printJoin (node_modules/babel-generator/lib/printer.js:368:12)
     at Generator.printList (node_modules/babel-generator/lib/printer.js:432:17
```

**Comment by bkniffler** [comment]
Any progress here? This is a nasty bug.

**Comment by xiehurricane** [comment]
Temporary,you can use this for css.
`import 'antd/dist/antd.min.css';`
and write babel config like this:
`plugins: ["transform-runtime", ["import", [{ "libraryName": "antd" }]]],`
It works for me。
