### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by nixuan** [ant-design/babel-plugin-import#69]
[
        "antd",
        {
          "style": "css",
          "libraryName": "antd-mobile"
        }
]

 at Buffer._append (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/buffer.js:78:25)
    at Buffer.append (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/buffer.js:55:10)
    at Generator._append (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:206:52)
    at Generator.word (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:131:10)
    at Generator.Identifier (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/generators/types.js:39:8)
    at /Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:295:23
    at Buffer.withSource (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/buffer.js:151:5)
    at Generator.withSource (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:294:10)
    at Generator.ImportSpecifier (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/generators/modules.js:22:8)
    at /Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:295:23
    at Buffer.withSource (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/buffer.js:151:5)
    at Generator.withSource (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:294:10)
    at Generator.printJoin (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:365:12)
    at Generator.printList (/Users/nixuan/workspace/php/lwechat/resources/assets/node_modules/babel-generator/lib/printer.js:429:17)

使用如上配置，指定style后，一直报 Cannot read property '0' of null 这样的错误
在issues里也看到别人报类似错误，不能自动引入css样式，尝试debug后发现
selectedMethods[methodName] = file.addImport(path, 'default');
if (style === true) { 
    file.addImport(path + '/style');
} else if (style === 'css') {
    _file.addImport(path + '/style/css', 'default_css')_
}
在上面代码段中加入第2个参数后就可以消除错误，但我对node这块的代码用法不太了解，想请作者有空能否确认下，谢谢

**Comment by sorrycc** [comment]
没加 [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) 引起的吗?

**Comment by nixuan** [comment]
确实没有加这个插件，但刚试了一下加这个插件还是报同样的错

**Comment by p2227** [comment]
duplicate #54

**Comment by bkniffler** [comment]
this could be closed..

**Comment by paranoidjk** [comment]
close for no response.

If you still got problem, feel free to reopen.
